### ISSUE TITLE
Creates just one traffic mirror session

### ISSUE THREAD

**Issue by buzen247** [aws-samples/aws-vpc-traffic-mirroring-source-automation#2]
**A reproducible test case or series of steps**
About 900 nodes in the account but I am interested in 20 which has a unique tags. Set up traffic mirroring with my already created NLB based target in us-west02 region.
```
---
tags:
- tagList: # At least one tag (pair of of {key, value}) is required
  - Key: Name # e.g. TagKey
    Value: mytag1 # required e.g. TagValue
  - Key: Name
    Value: mytag2

  targetId: tmt-xxxxxxxxxxx
  filterId: tmf-yyyyyyyyyyyy

```
**Any modifications you've made relevant to the bug**
Used a similar example to Example Scenario I
`sam deploy --s3-bucket my-s3-bucket --profile myawsprofile --s3-prefix vpc-mirror --region us-west-2 --capabilities CAPABILITY_IAM --stack-name vpc-mirror --parameter-overrides EnableTMExistingInstances=true EnableTMNewInstances=true EnableTMGuardDutyFindings=false`

**Issue**

1. Only a single traffic mirror session gets created each time I run sam deploy.
2. Deleting the stack and redeploying again produces the same result.
3. I was expecting about 20 mirror sessions to be created as I have two ec2 instances with <mytag1> tag key value.

**Feature request** 
Is it possible to include an AND for the tags related configuration ?
Example: Create a mirror session for an EC2 interface IF there is match for both Key:TAG1 and key:TAG2 on the instance tags
